import { Link } from 'react-router-dom'
import { ExternalLink, Sparkles } from 'lucide-react'
import type { EntityBrief } from '../../lib/api/entityBrief'

function List({ items }: { items: string[] }) {
  if (items.length === 0) return null
  return (
    <ul className="list-disc space-y-1 pl-4 text-sm text-slate-600 dark:text-slate-300">
      {items.map((item, i) => (
        <li key={i}>{item}</li>
      ))}
    </ul>
  )
}

function SubSection({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <h4 className="text-xs font-semibold uppercase tracking-wide text-slate-400 dark:text-slate-500">{title}</h4>
      <div className="mt-1.5">{children}</div>
    </div>
  )
}

/**
 * Renders exactly what the Gemini-backed provider returned, already
 * server-validated (worker/src/api/entityBriefApi.ts): every confirmedFacts
 * citation points at a real supplied event, whatToWatch is empty unless real
 * upcoming events existed, sourcesConfirming only lists sources actually
 * supplied. This component adds no interpretation of its own — confirmed
 * facts and AI interpretation are rendered as visually distinct sections,
 * never merged into one list.
 */
export function EntityBriefPanel({ brief }: { brief: EntityBrief }) {
  return (
    <div className="flex flex-col gap-4">
      <div className="flex flex-wrap items-center gap-2">
        <span className="inline-flex items-center gap-1.5 rounded-full bg-violet-500/10 px-2.5 py-1 text-xs font-medium text-violet-600 dark:text-violet-400">
          <Sparkles className="h-3.5 w-3.5" aria-hidden />
          AI Intelligence Summary
        </span>
      </div>

      <p className="text-sm font-medium text-slate-800 dark:text-slate-100">{brief.summary}</p>

      {brief.whatChanged && (
        <SubSection title="What changed recently">
          <p className="text-sm text-slate-600 dark:text-slate-300">{brief.whatChanged}</p>
        </SubSection>
      )}

      {brief.confirmedFacts.length > 0 && (
        <SubSection title="Confirmed facts">
          <ul className="flex flex-col gap-1.5">
            {brief.confirmedFacts.map((fact, i) => (
              <li key={i} className="text-sm text-slate-600 dark:text-slate-300">
                {fact.statement}{' '}
                <Link
                  to={`/feed/${encodeURIComponent(fact.eventId)}`}
                  className="inline-flex items-center gap-0.5 text-xs font-medium text-sky-500 hover:text-sky-600"
                >
                  source <ExternalLink className="h-3 w-3" aria-hidden />
                </Link>
              </li>
            ))}
          </ul>
        </SubSection>
      )}

      {brief.aiInterpretation.length > 0 && (
        <div className="rounded-lg border border-violet-200 bg-violet-50/60 p-3 dark:border-violet-900/50 dark:bg-violet-950/20">
          <div className="text-xs font-semibold text-violet-700 dark:text-violet-400">AI interpretation (not independently confirmed)</div>
          <List items={brief.aiInterpretation} />
        </div>
      )}

      {brief.whatToWatch.length > 0 && (
        <SubSection title="What to watch next">
          <List items={brief.whatToWatch} />
        </SubSection>
      )}

      {brief.sourcesConfirming.length > 0 && (
        <SubSection title="Sources confirming">
          <div className="flex flex-wrap gap-1.5">
            {brief.sourcesConfirming.map((source) => (
              <span key={source} className="rounded-full bg-slate-100 px-2 py-0.5 text-xs text-slate-600 dark:bg-slate-800 dark:text-slate-300">
                {source}
              </span>
            ))}
          </div>
        </SubSection>
      )}

      <p className="border-t border-slate-100 pt-2 text-xs text-slate-400 dark:border-slate-800 dark:text-slate-500">
        Generated by {brief.model} · {new Date(brief.generatedAt).toLocaleString()} — built only from this entity's real tracked events, not a substitute for editorial judgment.
      </p>
    </div>
  )
}
