-- Phase 6: Database Schema
-- User-owned tables. Reference auth.users(id) — Supabase's built-in auth
-- table, present on every Supabase project by default even though no
-- auth UI/flow exists in the frontend yet (see docs/decisions/0004-database-schema.md).

create table public.watchlists (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  name text not null,
  -- Shaped like the frontend's existing mock SavedSearch concept
  -- (src/lib/mockData.ts): e.g. {"categories": ["conflicts"], "minSeverity": "high"}.
  filters jsonb not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.watchlists is
  'Saved search criteria — the persistent config. See `alerts` for the materialized "this event matched" instances.';

create index watchlists_user_id_idx on public.watchlists (user_id);

-- Materialized "this event matched this watchlist" instances — generated by
-- a future matching job (not built in this phase), not written by hand.
create table public.alerts (
  id uuid primary key default gen_random_uuid(),
  watchlist_id uuid not null references public.watchlists (id) on delete cascade,
  normalized_event_id text not null references public.normalized_events (id) on delete cascade,
  triggered_at timestamptz not null default now(),
  read boolean not null default false,
  unique (watchlist_id, normalized_event_id)
);

create index alerts_watchlist_id_idx on public.alerts (watchlist_id);

-- Broader than watchlist matches — any system notification to a user
-- (digest ready, export complete, etc.), not just alert triggers.
create table public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  type text not null,
  payload jsonb not null default '{}',
  read boolean not null default false,
  created_at timestamptz not null default now()
);

create index notifications_user_id_idx on public.notifications (user_id);

create table public.bookmarks (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  normalized_event_id text not null references public.normalized_events (id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (user_id, normalized_event_id)
);

comment on table public.bookmarks is
  'Backs the per-card Bookmark button already built in the frontend (src/components/feed/EventCard.tsx) — currently local component state, not yet wired to persistence.';

create index bookmarks_user_id_idx on public.bookmarks (user_id);
